import pollyImage from "@/assets/polly-editorial.jpg";
import { Cta } from "./desafio-sections";

export function ProfileSection() {
  return <section className="page-section"><div className="grid items-start gap-7 md:grid-cols-[.7fr_1.3fr]"><div className="glass overflow-hidden rounded-2xl p-2"><img src={pollyImage} alt="Polly Takao" width={736} height={912} loading="lazy" className="aspect-[4/5] w-full rounded-xl object-cover"/></div><div><p className="eyebrow">Quem irá te acompanhar nessa jornada?</p><h2>Polly Takao</h2><div className="mt-5 space-y-4 text-sm leading-relaxed text-muted-foreground"><p>Sou a <strong className="text-foreground">Polly Takao</strong>, e depois de me frustrar ao emagrecer e engordar dezenas de vezes — num ciclo de efeitos sanfontes sem fim — eu resolvi estudar. Não era mais possível viver brigando com a balança o tempo todo.</p><p>Me formei Bacharel em Educação Física pela <strong className="text-foreground">USP</strong> e pela <strong className="text-foreground">Universidade do Porto</strong> em Portugal, e após testar várias teorias e métodos criei o programa "Mulher em Forma", que me fez emagrecer de forma definitiva e tem ajudado milhares de mulheres a emagrecerem de forma totalmente natural.</p><p>O método aborda a fisiologia exclusivamente feminina — algo que 90% dos programas de emagrecimento ignora completamente. Por isso funciona onde outros falharam.</p><p>Minha missão de vida é ajudar milhares de outras mulheres a emagrecerem e pararem de brigar com a balança.</p></div><div className="mt-5 inline-flex items-center gap-2 rounded-lg border border-coral/30 bg-coral/10 px-4 py-3 text-sm font-semibold">🏆 Premiado pela USP — Top 3 no Brasil</div></div></div></section>;
}

export function FinalCta({ onCta }: { onCta: () => void }) {
  return <section className="mx-auto max-w-5xl px-4 py-12 text-center"><div className="glass rounded-2xl p-7 sm:p-12"><span className="eyebrow">⏰ Vagas Limitadas — Início Segunda-feira</span><h2 className="mt-4">Este é o momento de escolher:</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-relaxed text-muted-foreground">Continuar lutando contra seu próprio corpo, seguindo dietas que ignoram seus hormônios, se sentindo frustrada e sem resultados…</p><p className="font-display my-4 text-4xl text-primary">OU</p><p className="mx-auto max-w-2xl font-semibold">Finalmente trabalhar COM seus hormônios e ver resultados em apenas 7 dias.</p><p className="mt-3 text-sm text-muted-foreground">📅 Início: próxima Segunda-feira</p><div className="mt-7"><Cta onClick={onCta}>QUERO GARANTIR MINHA VAGA AGORA →</Cta></div></div></section>;
}