import camilaImage from "@/assets/camila-nogueira.jpg";
import { Cta } from "./desafio-sections";

export function ProfileSection() {
  return <section className="page-section"><div className="grid items-start gap-7 md:grid-cols-[.7fr_1.3fr]"><div className="glass overflow-hidden rounded-2xl p-2"><img src={camilaImage} alt="Camila Nogueira, criadora do método 7D Seca & Desincha" width={736} height={912} loading="lazy" className="aspect-[4/5] w-full rounded-xl object-cover"/></div><div><p className="eyebrow">Quem irá te acompanhar nessa jornada?</p><h2>Camila Nogueira</h2><p className="mt-2 text-sm font-semibold text-primary">Criadora do método 7D Seca & Desincha</p><div className="mt-5 space-y-4 text-sm leading-relaxed text-muted-foreground"><p className="text-foreground font-semibold">"Eu estava cansada de ver mulheres começando uma dieta na segunda-feira e desistindo antes mesmo de chegar ao fim da semana."</p><p>Cardápios impossíveis. Treinos de uma hora. Listas de proibições que ninguém consegue seguir numa terça-feira comum, com trabalho, casa e cansaço. E quando a mulher desistia, a culpa sempre caía nela.</p><p>Mas eu percebi uma coisa: o problema não era falta de força de vontade. <strong className="text-foreground">O problema era a rotina complicada demais para caber na vida real.</strong></p><p>Por isso criei o 7D. <strong className="text-foreground">7 dias. Alimentação organizada. Até 20 minutos de movimento por dia. Uma missão de cada vez.</strong> Sem precisar virar outra pessoa da noite para o dia.</p><p>Você não precisa transformar sua vida inteira para começar a transformar sua rotina.</p><p className="text-foreground font-semibold">Pare de complicar. Pare de começar e desistir. Faça o básico durante 7 dias e veja como sua rotina pode mudar.</p></div></div></div></section>;
}

export function FinalCta({ onCta }: { onCta: () => void }) {
  return <section className="mx-auto max-w-5xl px-4 py-12 text-center"><div className="glass rounded-2xl p-7 sm:p-12"><span className="eyebrow">⏰ Vagas Limitadas — Início Segunda-feira</span><h2 className="mt-4">Este é o momento de escolher:</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-relaxed text-muted-foreground">Continuar lutando contra seu próprio corpo, seguindo dietas que ignoram seus hormônios, se sentindo frustrada e sem resultados…</p><p className="font-display my-4 text-4xl text-primary">OU</p><p className="mx-auto max-w-2xl font-semibold">Finalmente trabalhar COM seus hormônios e ver resultados em apenas 7 dias.</p><p className="mt-3 text-sm text-muted-foreground">📅 Início: próxima Segunda-feira</p><div className="mt-7"><Cta onClick={onCta}>QUERO GARANTIR MINHA VAGA AGORA →</Cta></div></div></section>;
}